baseurl = "https://vescovaccio.github.io"

languageCode = "en-GB"
title = "Vescovo Page"
theme = "vescovo"

[params]
  author = "Adam Bishop"
  description = "My Vescovo Page"

  gh_url = "https://api.github.com/users"
  gh_user = "vescovaccio"
